---
title: "Reflection"
author: "Victoria Seng"
---

---
layout: post
---

**What (if anything) has changed about what you think a data scientist is and what they do?**

I've gained additional appreciation for things like computational cost and that more complicated is not always better. So I guess data scientists do the cost benefit analysis of model complexity versus accuracy and computational cost using their familiarity with the data set and the results of testing.

**What are your current thoughts in terms of using R for data science - do you think you'll continue to use R going forward?  Why or why not?**

I like R and will definitely use it moving forward. Its free and open source, which means I can work on my own projects without a big investment, and I wouldn't have to have my employer make an investment for me to use it at work.

**What things are you going to do differently in practice now that you've had this course?**

I'll likely try harder to optimize my code to run faster. And I'll be able to start playing with modeling at work. 

```{r render, include = FALSE, eval = FALSE}
rmarkdown::render("./_Rmd/2021-11-30-Reflection.Rmd", 
          output_format = "github_document",
          output_dir = "./_posts", 
          output_options = list(
            toc = FALSE, 
            html_preview = FALSE, 
            keep_html = FALSE
            )
          )
```